export enum genre {
    Action = 'Action',
    Adventure = 'Adventure',
    Animation = 'Animation',
    Comedy = 'Comedy',
    Crime = 'Crime',
    Documentary = 'Documentary',
    Drama = 'Drama',
    Family = 'Family',
    Fantasy = 'Fantasy',
    History = 'History',
    Horror = 'Horror',
    Music = 'Music',
    Mystery = 'Myster',
    Romance = 'Romance',
    ScienceFiction = 'ScienceFiction',
    Thriller = 'Thriller',
    War = 'War',
    Western = 'Western',
}